// Secrets manager (P5a): a small Vault-like sim driven by a `vault` CLI on
// web-01. Secrets are generated, stored and rotated inside the world state —
// the whole point is that no human ever types or sees a production secret.
import { World, VaultState, VaultSecret, OutLine } from '../types';
import { hashStr } from './docker';
import * as fs from './fs';

export function ensureVault(world: World): VaultState {
  if (!world.vault) {
    world.vault = { enabled: false, enabledAtMin: 0, secrets: {}, credsLive: false };
  }
  return world.vault;
}

function secretOf(world: World, path: string): VaultSecret | undefined {
  return ensureVault(world).secrets[path];
}

function genValue(world: World, path: string, salt: string): string {
  return 'db-vlt-' + hashStr(path + salt + world.nowMin).slice(0, 20);
}

/** Store a managed secret (generates the value internally). */
export function putSecret(world: World, path: string): { ok: boolean; message: string } {
  const v = ensureVault(world);
  if (!v.enabled) return { ok: false, message: 'vault is not enabled — run `vault status` first' };
  if (v.secrets[path]) return { ok: false, message: `secret already exists at ${path} (use vault rotate)` };
  v.secrets[path] = {
    path,
    value: genValue(world, path, 'put'),
    createdAtMin: world.nowMin,
    rotatedAtMin: world.nowMin,
    rotations: 0,
    dynamicLeases: 0
  };
  world.audit.push({ t: world.nowMin, actor: world.session.user, kind: 'vault', text: `Secret stored at ${path} (value generated by the vault, never displayed)` });
  return { ok: true, message: `secret written: ${path}` };
}

/** Rotate a secret: new value, old one dies everywhere it was valid. */
export function rotateSecret(world: World, path: string): { ok: boolean; message: string } {
  const v = ensureVault(world);
  const s = secretOf(world, path);
  if (!s) return { ok: false, message: `no secret at ${path}` };
  s.value = genValue(world, path, 'rot' + s.rotations);
  s.rotations += 1;
  s.rotatedAtMin = world.nowMin;
  if (world.flags.vaultLeakDetected && !world.flags.vaultLeakRevoked) {
    world.flags.vaultLeakRevoked = true;
    world.audit.push({ t: world.nowMin, actor: world.session.user, kind: 'vault', text: 'ROTATION AFTER LEAK: the leaked value is now dead — it authenticates nothing' });
  }
  if (v.credsLive) {
    world.audit.push({ t: world.nowMin, actor: 'vault', kind: 'vault', text: `Zero-downtime rotation: dynamic credentials for ${path} re-issued; the database accepted the new pair mid-flight` });
  }
  return { ok: true, message: `rotated ${path} (rotation #${s.rotations})` };
}

/** Issue dynamic DB credentials against a secret (short-lived, auto-renewed). */
export function leaseCreds(world: World, path: string): { ok: boolean; message: string } {
  const v = ensureVault(world);
  const s = secretOf(world, path);
  if (!s) return { ok: false, message: `no secret at ${path}` };
  s.dynamicLeases += 1;
  v.credsLive = true;
  world.audit.push({ t: world.nowMin, actor: world.session.user, kind: 'vault', text: `Dynamic credentials leased for ${path} (TTL 60m, auto-renewed): the app now authenticates with vault-issued creds, not a file on disk` });
  return { ok: true, message: `lease issued for ${path} (dynamic, TTL 60m, auto-renewed)` };
}

/** Scan the filesystem and git history for copies of the current secret value. */
export function scanForLeaks(world: World): { leaked: boolean; message: string; hits: string[] } {
  const v = ensureVault(world);
  const hits: string[] = [];
  for (const s of Object.values(v.secrets)) {
    // honest check: any file on web-01 containing the live value
    for (const host of Object.values(world.hosts)) {
      for (const path of ['/opt/app/.env', '/opt/app/config.js', '/opt/app/notes-old.txt']) {
        const content = fs.readFile(host.fs, path);
        if (content && content.includes(s.value)) hits.push(`${host.id}:${path}`);
      }
    }
    // git history: a commit tree containing the literal value
    const repo = world.git['/opt/app'];
    if (repo && Object.values(repo.commits).some((c) => Object.values(c.tree).some((t) => typeof t === 'string' && t.includes(s.value)))) {
      hits.push('/opt/app git history (a commit contains the secret)');
    }
  }
  if (hits.length) {
    world.flags.vaultLeakDetected = true;
    world.audit.push({ t: world.nowMin, actor: world.session.user, kind: 'vault', text: `LEAK SCAN: ${hits.length} occurrence(s) of live secret material outside the vault: ${hits.join(', ')}` });
    return { leaked: true, message: 'live secret material found outside the vault — rotate to invalidate it', hits };
  }
  return { leaked: false, message: 'no secret material found outside the vault', hits };
}

// ------------------------------------------------------------------
// `vault` CLI
// ------------------------------------------------------------------
export interface VaultResult { lines: OutLine[]; code: number }

export function vaultCmd(world: World, argv: string[]): VaultResult {
  const v = ensureVault(world);
  const e = (t: string): VaultResult => ({ lines: [{ text: t, cls: 'err' }], code: 1 });
  const sub = argv[1];

  if (!v.enabled && sub !== 'status') {
    return e('vault: the secrets engine is not enabled — run `vault status` to initialize it');
  }

  switch (sub) {
    case undefined:
    case 'help':
    case '--help':
      return {
        lines: [
          { text: 'vault — secrets manager (simulated)', cls: 'hdr' },
          { text: 'status                   initialize + show seal state and secrets' },
          { text: 'put <path>               store a managed secret (value generated internally)' },
          { text: 'rotate <path>            issue a new value; the old one dies everywhere' },
          { text: 'lease <path>             issue dynamic DB credentials against a secret' },
          { text: 'scan                     scan filesystem + git history for leaked material' }
        ], code: 0
      };
    case 'status': {
      if (!v.enabled) {
        v.enabled = true;
        v.enabledAtMin = world.nowMin;
        world.audit.push({ t: world.nowMin, actor: world.session.user, kind: 'vault', text: 'Secrets manager initialized (kv + database engines enabled)' });
      }
      const lines: OutLine[] = [
        { text: 'Key             Value', cls: 'hdr' },
        { text: 'Seal Type       shamir' },
        { text: 'Initialized     true' },
        { text: 'Sealed          false' },
        { text: `Storage         in-world (backed by the audit log)` }
      ];
      const secrets = Object.values(v.secrets);
      if (secrets.length) {
        lines.push({ text: '', cls: undefined }, { text: '--- secrets ---', cls: 'hdr' });
        for (const s of secrets) {
          lines.push({ text: `${s.path}   rotations=${s.rotations}  leases=${s.dynamicLeases}  last_rotated=${s.rotatedAtMin === s.createdAtMin ? 'never' : 'min ' + s.rotatedAtMin}` });
        }
        lines.push({ text: `dynamic DB creds: ${v.credsLive ? 'LIVE (app authenticates via vault)' : 'not leased'}`, cls: v.credsLive ? 'ok' : 'dim' });
      }
      return { lines, code: 0 };
    }
    case 'put': {
      const path = argv[2];
      if (!path) return e('usage: vault put <path>');
      const r = putSecret(world, path);
      if (!r.ok) return e(r.message);
      return { lines: [
        { text: `Key              Value`, cls: 'hdr' },
        { text: `created          ${path}` },
        { text: `value            <generated — 24 bytes, never displayed>` },
        { text: `deletion_after   0s` }
      ], code: 0 };
    }
    case 'rotate': {
      const path = argv[2];
      if (!path) return e('usage: vault rotate <path>');
      const r = rotateSecret(world, path);
      if (!r.ok) return e(r.message);
      return { lines: [{ text: `Success! Rotated ${path} — new value generated, old value revoked`, cls: 'ok' }], code: 0 };
    }
    case 'lease': {
      const path = argv[2];
      if (!path) return e('usage: vault lease <path>');
      const r = leaseCreds(world, path);
      if (!r.ok) return e(r.message);
      return { lines: [
        { text: `Key               Value`, cls: 'hdr' },
        { text: `lease_id          database/${path.split('/').pop()}/<dynamic>` },
        { text: `username          v-app-<dynamic>` },
        { text: `ttl               60m (auto-renewed)` },
        { text: `note              the app picks these up on next connect — no .env on disk`, cls: 'dim' }
      ], code: 0 };
    }
    case 'scan': {
      const r = scanForLeaks(world);
      const lines: OutLine[] = [{ text: 'Scanning filesystem and git history for secret material…', cls: 'dim' }];
      if (r.leaked) {
        for (const h of r.hits) lines.push({ text: `  LEAK: ${h}`, cls: 'err' });
        lines.push({ text: 'Remediation: `vault rotate <path>` — the leaked value dies the moment you do', cls: 'warn' });
        return { lines, code: 1 };
      }
      lines.push({ text: 'Clean: no secret material outside the vault', cls: 'ok' });
      return { lines, code: 0 };
    }
    default:
      return e(`unknown command "${sub}" — try vault help`);
  }
}
